/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.ratu.sorter;


import com.ratu.sorter.domain.Person;
import org.junit.Test;

import java.util.ArrayList;
import java.util.List;

import static org.junit.Assert.assertEquals;

public class SorterTest {
    @Test
    public void testShouldReadNamesFromFileAndSortThemAndWriteToConsoleAndFile() {
        Sorter.main(new String[]{"./test-names-list.txt"});

        List<Person> expectedPeople = new ArrayList<>();
        expectedPeople.add(new Person("Battelle", "Erna Dorey"));
        expectedPeople.add(new Person("Franzel", "Flori Chaunce"));
        expectedPeople.add(new Person("Iddins", "Orson Milka"));

        IOUtil ioUtil = new IOUtil();
        List<Person> actualPeople = ioUtil.readPeopleFromFile("./sorted-names-list.txt");

        assertEquals( expectedPeople.toString(),actualPeople.toString());
    }
}
