/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.ratu.sorter;

import org.junit.Test;
import static org.junit.Assert.*;

public class SorterTest {
    @Test public void testSomeLibraryMethod() {
        assertTrue("dummy test", true);
    }
}
